controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_controller:
      type: position_controllers/JointGroupPositionController

    wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

swerve_controller:
  ros__parameters:
    joints:
      - lf_swerve_joint
      - rf_swerve_joint
      - rr_swerve_joint
      - lr_swerve_joint
    interface_name: position

wheel_controller:
  ros__parameters:
    joints:
      - lf_wheel_joint
      - rf_wheel_joint
      - rr_wheel_joint
      - lr_wheel_joint
    interface_name: velocity

gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      lf_swerve_joint: {p: 10.0, i: 0.0, d: 0.05}
      rf_swerve_joint: {p: 10.0, i: 0.0, d: 0.05}
      rr_swerve_joint: {p: 10.0, i: 0.0, d: 0.05}
      lr_swerve_joint: {p: 10.0, i: 0.0, d: 0.05}
      lf_wheel_joint: {p: 10.0, i: 0.0, d: 0.05}
      rf_wheel_joint: {p: 10.0, i: 0.0, d: 0.05}
      rr_wheel_joint: {p: 10.0, i: 0.0, d: 0.05}
      lr_wheel_joint: {p: 10.0, i: 0.0, d: 0.05}