mesh_files:
  package: swerve_drive_description

  base:
    visual:
      path: meshes/yhs_fw01/base_link.STL
    collision:
      path: meshes/yhs_fw01/base_link.STL

  swerve:
    visual:
      path: meshes/yhs_fw01/swerve_link.STL
    collision:
      path: meshes/yhs_fw01/swerve_link.STL

  wheel:
    visual:
      path: meshes/yhs_fw01/wheel_link.STL
    collision:
      path: meshes/yhs_fw01/wheel_link.STL